FOOT_CENTER_TO_BEV_FRAME_BOTTOM_DISTANCE = 90

WALK_PATH_TO_FIELD_EDGE_DEFAULT_MM = 200

WALK_PATH_TO_FIELD_EDGE_MINIMUM_MM = 150

WALK_PATH_TO_FIELD_EDGE_MAXIMUM_MM = 250

BALL_APPROACH_THRESHOLD = 100